name: Cross compile and publish ARM64 package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - name: Check out XNNPACK
        uses: actions/checkout@v3
        with:
          repository: dp0/XNNPACK
          path: XNNPACK
          ref: 1004acaa3a5c0f515a3f7b229aef1dabe31472a4
        
      - name: Check out OnnxStream
        uses: actions/checkout@v3
        with:
          path: OnnxStream

      - name: Extract version
        id: control-version
        run: |
          version=$(grep '^Version:' $GITHUB_WORKSPACE/OnnxStream/debian/control | cut -d ' ' -f 2)
          echo "CONTROL_VERSION=$version" | tee -a $GITHUB_OUTPUT
    
      - name: Install cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Cross compile XNNPACK
        run: |
          mkdir XNNPACK/build && cd $GITHUB_WORKSPACE/XNNPACK/build
          cmake -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/XNNPACK/cmake/aarch64.toolchain -DXNNPACK_BUILD_TESTS=OFF -DXNNPACK_BUILD_BENCHMARKS=OFF $GITHUB_WORKSPACE/XNNPACK
          cmake --build . --config Release -j $(nproc)
          find ~+ -name "*.a"

      - name: Cross compile OnnxStream
        run: |
          mkdir OnnxStream/build && cd $GITHUB_WORKSPACE/OnnxStream/build
          cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DXNNPACK_DIR=$GITHUB_WORKSPACE/XNNPACK $GITHUB_WORKSPACE/OnnxStream/src
          cmake --build . --config Release
          find ~+

      - name: Create Debian package
        run: |
          mkdir -p $GITHUB_WORKSPACE/package/DEBIAN
          cp -r $GITHUB_WORKSPACE/OnnxStream/debian/control $GITHUB_WORKSPACE/package/DEBIAN/
          mkdir -p $GITHUB_WORKSPACE/package/usr/bin
          cp $GITHUB_WORKSPACE/OnnxStream/build/sd $GITHUB_WORKSPACE/package/usr/bin/onnxstream
          aarch64-linux-gnu-strip --strip-unneeded $GITHUB_WORKSPACE/package/usr/bin/onnxstream
          mkdir -p $GITHUB_WORKSPACE/package/usr/share/doc/onnxstream
          cp $GITHUB_WORKSPACE/OnnxStream/LICENSE $GITHUB_WORKSPACE/package/usr/share/doc/onnxstream/LICENSE
          cp $GITHUB_WORKSPACE/XNNPACK/LICENSE $GITHUB_WORKSPACE/package/usr/share/doc/onnxstream/LICENSE.XNNPACK
          cp $GITHUB_WORKSPACE/OnnxStream/debian/changelog $GITHUB_WORKSPACE/package/usr/share/doc/onnxstream/changelog
          gzip -9n $GITHUB_WORKSPACE/package/usr/share/doc/onnxstream/changelog
          cp $GITHUB_WORKSPACE/OnnxStream/debian/copyright $GITHUB_WORKSPACE/package/usr/share/doc/onnxstream/copyright
          sudo chown -R root:root $GITHUB_WORKSPACE/package/
          dpkg-deb --build $GITHUB_WORKSPACE/package $GITHUB_WORKSPACE/onnxstream_${{ steps.control-version.outputs.CONTROL_VERSION }}_arm64.deb
          
      - name: Create release and upload package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/OnnxStream
          gh release create v${{ steps.control-version.outputs.CONTROL_VERSION }} $GITHUB_WORKSPACE/onnxstream_${{ steps.control-version.outputs.CONTROL_VERSION }}_arm64.deb --title "Release v${{ steps.control-version.outputs.CONTROL_VERSION }}"
